version: '3.4'

services:
  inventorymanager.api:
    image: ${DOCKER_REGISTRY-}inventorymanagerapi
    build:
      context: .
      dockerfile: API/InventoryManager.API/Dockerfile
    ports:
      - "61408:80"
      - "5281:5280"
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"  

